#!/usr/bin/env tsx
/**
 * Standalone backtest runner.
 *
 * Previously `runBacktest()` was reachable only from inside the daily-refresh
 * cron, so measuring the model meant also refetching fixtures, rewriting
 * predictions and pulling odds. That made the baseline expensive to obtain and
 * impossible to reproduce, which is why no baseline exists.
 *
 * This runs evaluation and backtest only. It writes PredictionEvaluation and
 * PredictionBacktestRun rows; it does not touch fixtures, odds or predictions.
 *
 * IMPORTANT: this measures whatever PredictionSnapshot rows already exist. Rows
 * generated by different engine versions are not comparable. Until
 * `modelVersion` lands on PredictionSnapshot (gap G9), treat any result from a
 * mixed-generation table as indicative only, and say so when reporting it.
 *
 * Usage:
 *   pnpm tsx scripts/backtest.ts
 *   pnpm tsx scripts/backtest.ts --window 180 --stake 10
 *   pnpm tsx scripts/backtest.ts --json > baseline.json
 */
// MUST stay first: populates process.env before the Prisma client is evaluated.
import { databaseHost, loadedEnvFile } from './load-env';
import { prisma } from '@apexpredix/db';
import { runBacktest } from '../lib/prediction-engine/backtest';

function arg(name: string, fallback?: string): string | undefined {
  const index = process.argv.indexOf(`--${name}`);
  return index >= 0 ? process.argv[index + 1] : fallback;
}

const windowDays = Number(arg('window', '90'));
const stake = Number(arg('stake', '10'));
const asJson = process.argv.includes('--json');

function percent(value: number) {
  return `${(value * 100).toFixed(2)}%`;
}

async function main() {
  if (!process.env.DATABASE_URL) {
    console.error(
      loadedEnvFile
        ? `Loaded ${loadedEnvFile} but DATABASE_URL is not in it. Pass --env-file <path>.`
        : 'No env file found (looked for apps/web/.env.local, .env.local, .env). Pass --env-file <path>.',
    );
    process.exit(1);
  }

  if (!Number.isFinite(windowDays) || windowDays <= 0) {
    console.error(`--window must be a positive number of days (got ${arg('window')})`);
    process.exit(1);
  }

  if (!asJson) {
    console.log(`env:      ${loadedEnvFile ?? 'process environment'}`);
    console.log(`database: ${databaseHost()}`);
    console.log(`window:   ${windowDays} days | stake: ${stake}\n`);
  }

  const snapshotCount = await prisma.predictionSnapshot.count();
  const settledCount = await prisma.predictionSnapshot.count({ where: { fixture: { result: { isNot: null } } } });

  if (settledCount === 0) {
    const message =
      `No settled predictions to evaluate (${snapshotCount} snapshots, 0 with results). ` +
      'A baseline cannot be produced yet. Run the daily-refresh cron and wait for fixtures to finish.';
    if (asJson) console.log(JSON.stringify({ status: 'NO_DATA', snapshotCount, settledCount, message }, null, 2));
    else console.error(message);
    await prisma.$disconnect();
    process.exit(asJson ? 0 : 1);
  }

  const result = await runBacktest(prisma, { windowDays, stake });
  const buckets = await prisma.predictionCalibrationBucket.findMany({
    where: { runId: result.run.id },
    orderBy: { lowerBound: 'asc' },
  });

  if (asJson) {
    console.log(
      JSON.stringify(
        {
          status: 'OK',
          generatedAt: new Date().toISOString(),
          windowDays,
          stake,
          snapshotCount,
          settledCount,
          evaluatedThisRun: result.evaluatedNow,
          run: result.run,
          calibrationBuckets: buckets,
          caveats: [
            'Sample may mix engine generations until PredictionSnapshot.modelVersion exists (gap G9).',
            'ROI is only meaningful if the odds used were genuinely available pre-kickoff.',
            'No confidence intervals are computed yet — do not quote an edge from this alone.',
          ],
        },
        null,
        2,
      ),
    );
    await prisma.$disconnect();
    return;
  }

  const run = result.run;
  console.log('BASELINE');
  console.log('='.repeat(58));
  console.log(`  sample size          ${run.sampleSize}`);
  console.log(`  evaluated this run   ${result.evaluatedNow}`);
  console.log(`  hit rate             ${percent(run.hitRate)}`);
  console.log(`  Brier score          ${run.brierScore.toFixed(4)}   (lower is better)`);
  console.log(`  log loss             ${run.logLoss.toFixed(4)}   (lower is better)`);
  console.log(`  calibration error    ${run.calibrationError.toFixed(4)}   (lower is better)`);
  console.log(`  average confidence   ${percent(run.averageConfidence)}`);
  console.log(`  average edge         ${percent(run.averageEdge)}`);
  console.log(`  ROI                  ${percent(run.roi)}`);
  console.log(`  net profit           ${run.netProfit.toFixed(2)} (staked ${run.totalStaked.toFixed(2)})`);

  console.log('\nCALIBRATION');
  console.log('='.repeat(58));
  console.log('  bucket      n     predicted    observed     error');
  for (const bucket of buckets) {
    console.log(
      `  ${bucket.bucket.padEnd(10)} ${String(bucket.sampleSize).padEnd(5)} ` +
        `${percent(bucket.averageProbability).padEnd(12)} ${percent(bucket.observedRate).padEnd(12)} ` +
        `${bucket.calibrationError.toFixed(4)}`,
    );
  }

  console.log('\nCAVEATS');
  console.log('='.repeat(58));
  if (run.sampleSize < 100) {
    console.log(`  ! Sample size ${run.sampleSize} is below 100. These figures are not publishable.`);
  }
  console.log('  - Sample may mix engine generations until modelVersion exists (G9).');
  console.log('  - ROI assumes the recorded odds were available pre-kickoff.');
  console.log('  - No confidence intervals computed. Do not claim an edge from this alone.\n');

  await prisma.$disconnect();
}

main().catch(async (error) => {
  console.error(error);
  await prisma.$disconnect();
  process.exit(1);
});
